### ISSUE TITLE
Travis

### ISSUE THREAD

**Issue by jrfnl** [twoelevenjay/CMB2-Admin-Extension#6]
Hi Leon,

I noticed you where trying to get travis working. What are the tasks you would like travis to do ?

If you like I can add a script which will work & do the following:
* lint the PHP files
* lint and hint any JS files according to the WP standards
* run PHPCS with the WP coding standards

If at some point you'd want to add unit tests to the repo as well, I can set that up too (but not before as it's useless running the test suite if you have no tests for the plugin).

Let me know if that would be helpful.

**Comment by jrfnl** [comment]
Oh and you may want to reset the master to before the trial & error & force push it  ?

**Comment by twoelevenjay** [comment]
I have finally been giving the plugin some attention. I would very much appreciate it if you could get Travis working. I did reset it to before the trial and error thanks for the suggestion.
